name:                sgd
version:             0.2.3
github:              "kawu/sgd"
license:             BSD3
author:              "Jakub Waszczuk"
maintainer:          "waszczuk.kuba@gmail.com"
copyright:           "2012-2019 IPI PAN, Jakub Waszczuk"

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
synopsis:            Stochastic gradient descent
category:            Math, Algorithms

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kawu/sgd#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5 && < 0.7
- vector
- random
- primitive
- logfloat
- monad-par
- deepseq

library:
  source-dirs: src
